spring:
  application:
    name: service-customer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: soms
      config:
        import-check:
          enabled: false
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#    username:
#    password:

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8010